version: '2'
services:
    bot:
        build: .
        restart: unless-stopped
        command: npm run start
    mongo:
        image: mongo
        restart: unless-stopped
        ports:
            - $MONGO_PORT:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
            MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
            MONGO_INITDB_USERNAME: $MONGO_USER
            MONGO_INITDB_PASSWORD: $MONGO_PASSWORD
            MONGO_INITDB_DATABASE: $MONGO_DB
        volumes:
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
