name: Deployment workflow
on:
    workflow_dispatch:
jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote ssh commands
              uses: appleboy/ssh-action@master
              env:
                  GITHUB_REPOSITORY: '${{ github.repository }}'
                  GITHUB_PERSONAL_ACCESS_TOKEN: '${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}'
                  WORKING_DIRECTORY: '${{ secrets.WORKING_DIRECTORY }}'
                  DISCORD_TOKEN: '${{ secrets.DISCORD_TOKEN }}'
                  MONGO_PORT: '${{ secrets.MONGO_PORT }}'
                  MONGO_ROOT_USER: '${{ secrets.MONGO_ROOT_USER }}'
                  MONGO_ROOT_PASSWORD: '${{ secrets.MONGO_ROOT_PASSWORD }}'
                  MONGO_USER: '${{ secrets.MONGO_USER }}'
                  MONGO_PASSWORD: '${{ secrets.MONGO_PASSWORD }}'
                  MONGO_DB: '${{ secrets.MONGO_DB }}'
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  envs: 
                  script: |
                      cd $WORKING_DIRECTORY
                      rm -rf ${GITHUB_REPOSITORY#*/}
                      git clone https://$GITHUB_PERSONAL_ACCESS_TOKEN@github.com/$GITHUB_REPOSITORY.git
                      cd ${GITHUB_REPOSITORY#*/}
                      echo "\
# Discord.js
DISCORD_TOKEN=$DISCORD_TOKEN

# MongoDB
MONGO_PORT=$MONGO_PORT
MONGO_ROOT_USER=$MONGO_ROOT_USER
MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
MONGO_USER=$MONGO_USER
MONGO_PASSWORD=$MONGO_PASSWORD
MONGO_DB=$MONGO_DB\
" > .env
                      docker-compose down
                      docker-compose build
                      docker-compose up -d
